language: csharp
script:
  - ./build.sh --verbosity=diagnostic

os:
  - linux
  - osx

# Ubuntu 16.04
sudo: required
dist: xenial

mono:
  - latest
dotnet: 2.1.502

cache:
  directories:
    - packages
    - tools
